import type { JSX } from 'preact';
import {
  Activity,
  AlarmClock,
  Anchor,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Axe,
  Banknote,
  Beer,
  BicepsFlexed,
  Bomb,
  BookOpenText,
  Bug,
  CalendarHeart,
  Camera,
  Cannabis,
  Cat,
  ChartGantt,
  ChartNetwork,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDownUp,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  Church,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleDot,
  CirclePause,
  CirclePlay,
  CircleX,
  Clapperboard,
  ClipboardCopy,
  Clock,
  Clover,
  Cog,
  Coins,
  Columns3,
  Compass,
  Copy,
  Crosshair,
  Crown,
  CupSoda,
  Dices,
  DoorOpen,
  Dot,
  Download,
  Drama,
  Droplet,
  Droplets,
  Ellipsis,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  FileDown,
  FileUp,
  Film,
  Flag,
  FlagTriangleRight,
  Flame,
  Footprints,
  Gem,
  Ghost,
  Rewind,
  GripVertical,
  GitBranch,
  Hammer,
  HandFist,
  HandHelping,
  Heart,
  HeartCrack,
  HeartHandshake,
  HeartPulse,
  Hourglass,
  Info,
  Keyboard,
  LayoutGrid,
  LibraryBig,
  Lightbulb,
  Link,
  List,
  ListChecks,
  ListFilter,
  ListRestart,
  Lock,
  LockOpen,
  Map as MapIcon,
  Maximize,
  Maximize2,
  Megaphone,
  MessageSquareQuote,
  MessagesSquare,
  MicVocal,
  Milestone,
  Minimize,
  Minimize2,
  Minus,
  Monitor,
  MonitorPlay,
  Moon,
  MoonStar,
  Network,
  NotebookPen,
  OctagonAlert,
  Orbit,
  Package,
  PanelRightClose,
  Pause,
  Pencil,
  PencilOff,
  PhoneCall,
  Play,
  Plus,
  Popcorn,
  Presentation,
  Quote,
  Rabbit,
  Radar,
  Redo2,
  Repeat,
  RotateCcw,
  Route,
  Rows3,
  Sailboat,
  Scan,
  ScanEye,
  ScanFace,
  ScrollText,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  Shrink,
  SkipBack,
  SkipForward,
  Skull,
  Slice,
  Smartphone,
  Sparkle,
  Sparkles,
  Sprout,
  Star,
  StickyNote,
  Sun,
  Sunrise,
  Sword,
  Swords,
  Syringe,
  TableOfContents,
  Target,
  TextSearch,
  Ticket,
  Timer,
  TimerReset,
  Trash,
  TriangleAlert,
  Turtle,
  Undo2,
  Upload,
  User,
  UserX,
  Users,
  Utensils,
  UtensilsCrossed,
  VenetianMask,
  Video,
  WandSparkles,
  Wind,
  Wine,
  Workflow,
  Wrench,
  X,
  Zap,
  ZoomIn,
  Ban,
  CircleQuestionMark,
  Contact,
  MapPin,
  MountainSnow,
  Plane,
  Ship,
  Store,
  TreePalm,
  Scroll,
  Tv,
  Waypoints,
  ZoomOut,
} from 'lucide-preact';
import type { LucideIcon, LucideProps } from 'lucide-preact';

type IconComp = LucideIcon | ((props: LucideProps) => JSX.Element);

/** Lucide has no bagel, so here is an everything bagel drawn to match: the ring, its side, the hole and seeds. */
function Bagel({ size = 24, strokeWidth = 2, class: cls, ...rest }: LucideProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width={strokeWidth}
      stroke-linecap="round"
      stroke-linejoin="round"
      class={['lucide', 'lucide-bagel', cls].filter(Boolean).join(' ')}
      {...(rest as Record<string, unknown>)}
    >
      <ellipse cx="12" cy="10.5" rx="10" ry="6" />
      <path d="M2 10.5v2.5c0 3.3 4.5 6 10 6s10-2.7 10-6v-2.5" />
      <ellipse cx="12" cy="10.5" rx="3" ry="1.5" />
      <path d="M6.5 8.6h.01M17.5 8.6h.01M7.6 12.9h.01M16.4 12.9h.01M12 6.4h.01" />
    </svg>
  );
}

const ICONS: Record<string, IconComp> = {
  activity: Activity,
  'alarm-clock': AlarmClock,
  anchor: Anchor,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  axe: Axe,
  banknote: Banknote,
  beer: Beer,
  'biceps-flexed': BicepsFlexed,
  bomb: Bomb,
  'book-open-text': BookOpenText,
  bug: Bug,
  'calendar-heart': CalendarHeart,
  camera: Camera,
  cannabis: Cannabis,
  cat: Cat,
  'chart-gantt': ChartGantt,
  'chart-network': ChartNetwork,
  check: Check,
  'check-check': CheckCheck,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-down-up': ChevronsDownUp,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'chevrons-up-down': ChevronsUpDown,
  church: Church,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-dashed': CircleDashed,
  'circle-dot': CircleDot,
  'circle-pause': CirclePause,
  'circle-play': CirclePlay,
  'circle-x': CircleX,
  clapperboard: Clapperboard,
  'clipboard-copy': ClipboardCopy,
  clock: Clock,
  clover: Clover,
  cog: Cog,
  coins: Coins,
  'columns-3': Columns3,
  compass: Compass,
  copy: Copy,
  crosshair: Crosshair,
  crown: Crown,
  'cup-soda': CupSoda,
  dices: Dices,
  bagel: Bagel,
  'door-open': DoorOpen,
  dot: Dot,
  download: Download,
  drama: Drama,
  droplet: Droplet,
  droplets: Droplets,
  ellipsis: Ellipsis,
  expand: Expand,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  'file-down': FileDown,
  'file-up': FileUp,
  film: Film,
  flag: Flag,
  'flag-triangle-right': FlagTriangleRight,
  flame: Flame,
  footprints: Footprints,
  gem: Gem,
  ghost: Ghost,
  rewind: Rewind,
  'grip-vertical': GripVertical,
  'git-branch': GitBranch,
  hammer: Hammer,
  'hand-fist': HandFist,
  'hand-helping': HandHelping,
  heart: Heart,
  'heart-crack': HeartCrack,
  'heart-handshake': HeartHandshake,
  'heart-pulse': HeartPulse,
  hourglass: Hourglass,
  info: Info,
  keyboard: Keyboard,
  'layout-grid': LayoutGrid,
  'library-big': LibraryBig,
  lightbulb: Lightbulb,
  link: Link,
  list: List,
  'list-checks': ListChecks,
  'list-filter': ListFilter,
  'list-restart': ListRestart,
  lock: Lock,
  'lock-open': LockOpen,
  map: MapIcon,
  maximize: Maximize,
  'maximize-2': Maximize2,
  megaphone: Megaphone,
  'message-square-quote': MessageSquareQuote,
  'messages-square': MessagesSquare,
  'mic-vocal': MicVocal,
  milestone: Milestone,
  minimize: Minimize,
  'minimize-2': Minimize2,
  minus: Minus,
  monitor: Monitor,
  'monitor-play': MonitorPlay,
  moon: Moon,
  'moon-star': MoonStar,
  network: Network,
  'notebook-pen': NotebookPen,
  'octagon-alert': OctagonAlert,
  orbit: Orbit,
  package: Package,
  'panel-right-close': PanelRightClose,
  pause: Pause,
  pencil: Pencil,
  'pencil-off': PencilOff,
  'phone-call': PhoneCall,
  play: Play,
  plus: Plus,
  popcorn: Popcorn,
  presentation: Presentation,
  quote: Quote,
  rabbit: Rabbit,
  radar: Radar,
  'redo-2': Redo2,
  repeat: Repeat,
  'rotate-ccw': RotateCcw,
  route: Route,
  'rows-3': Rows3,
  sailboat: Sailboat,
  scan: Scan,
  'scan-eye': ScanEye,
  'scan-face': ScanFace,
  'scroll-text': ScrollText,
  search: Search,
  settings: Settings,
  shield: Shield,
  'shield-check': ShieldCheck,
  shrink: Shrink,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  skull: Skull,
  slice: Slice,
  smartphone: Smartphone,
  sparkle: Sparkle,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  'sticky-note': StickyNote,
  sun: Sun,
  sunrise: Sunrise,
  sword: Sword,
  swords: Swords,
  syringe: Syringe,
  'table-of-contents': TableOfContents,
  target: Target,
  'text-search': TextSearch,
  ticket: Ticket,
  timer: Timer,
  'timer-reset': TimerReset,
  trash: Trash,
  'triangle-alert': TriangleAlert,
  turtle: Turtle,
  'undo-2': Undo2,
  upload: Upload,
  user: User,
  'user-x': UserX,
  users: Users,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  'venetian-mask': VenetianMask,
  video: Video,
  'wand-sparkles': WandSparkles,
  wind: Wind,
  wine: Wine,
  workflow: Workflow,
  wrench: Wrench,
  x: X,
  zap: Zap,
  'zoom-in': ZoomIn,
  ban: Ban,
  'circle-question-mark': CircleQuestionMark,
  contact: Contact,
  'map-pin': MapPin,
  'mountain-snow': MountainSnow,
  plane: Plane,
  ship: Ship,
  store: Store,
  'tree-palm': TreePalm,
  scroll: Scroll,
  tv: Tv,
  waypoints: Waypoints,
  'zoom-out': ZoomOut,
};

export function Icon({ name, size = 16, stroke = 2, class: cls }: { name: string; size?: number; stroke?: number; class?: string }) {
  const C = ICONS[name] ?? CircleDashed;
  return <C size={size} strokeWidth={stroke} class={cls} aria-hidden={true} />;
}

export const hasIcon = (name: string) => name in ICONS;
